In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
land_registry_folder = Path(
    "/Users/bibhrajsaha/uk-housing-intelligence-platform/data/raw/land_registry"
)

land_registry_files = sorted(
    land_registry_folder.glob("pp-*.csv")
)

land_registry_files

[PosixPath('/Users/bibhrajsaha/uk-housing-intelligence-platform/data/raw/land_registry/pp-2023.csv'),
 PosixPath('/Users/bibhrajsaha/uk-housing-intelligence-platform/data/raw/land_registry/pp-2024.csv'),
 PosixPath('/Users/bibhrajsaha/uk-housing-intelligence-platform/data/raw/land_registry/pp-2025.csv'),
 PosixPath('/Users/bibhrajsaha/uk-housing-intelligence-platform/data/raw/land_registry/pp-2026.csv')]

In [3]:
len(land_registry_files)

4

In [4]:
house_dfs = []

for file in land_registry_files:

    temp_df = pd.read_csv(
        file,
        header=None
    )

    house_dfs.append(temp_df)

house_df = pd.concat(
    house_dfs,
    ignore_index=True
)

In [5]:
house_df.columns = [
    "transaction_id",
    "price",
    "date_of_transfer",
    "postcode",
    "property_type",
    "old_new",
    "duration",
    "paon",
    "saon",
    "street",
    "locality",
    "town_city",
    "district",
    "county",
    "ppd_category_type",
    "record_status"
]

In [6]:
house_df.shape

(2816596, 16)

In [10]:
house_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2816596 entries, 0 to 2816595
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   transaction_id     str
 1   price              int64
 2   date_of_transfer   str
 3   postcode           str
 4   property_type      str
 5   old_new            str
 6   duration           str
 7   paon               str
 8   saon               str
 9   street             str
 10  locality           str
 11  town_city          str
 12  district           str
 13  county             str
 14  ppd_category_type  str
 15  record_status      str
dtypes: int64(1), str(15)
memory usage: 668.4 MB

In [11]:
house_df["price"].describe()

count    2.816596e+06
mean     3.934916e+05
std      1.257611e+06
min      1.000000e+00
25%      1.800000e+05
50%      2.800000e+05
75%      4.250000e+05
max      7.930200e+08
Name: price, dtype: float64

In [12]:
house_df.nsmallest(
    10,
    "price"
)[["price", "postcode", "town_city"]]

         price  postcode   town_city
90352        1   WN8 7AR       WIGAN
1018136      1    N7 0AA      LONDON
1025727      1   CV4 8NH    COVENTRY
2100609      1  SW18 2HG      LONDON
2100610      1  SW18 2HG      LONDON
2100611      1  SW18 2HG      LONDON
2100612      1  SW18 2HG      LONDON
2593623      1   WA3 2HZ  WARRINGTON
232        100  RM12 4TQ  HORNCHURCH
14654      100    E3 4SF      LONDON

In [13]:
house_df.nlargest(
    10,
    "price"
)[["price", "postcode", "town_city", "county"]]

             price  postcode town_city          county
2205784  793020000  WC2R 2PR    LONDON  GREATER LONDON
214863   267500000   W1S 2YF    LONDON  GREATER LONDON
216867   267500000   W1S 2YF    LONDON  GREATER LONDON
240984   267500000   W1S 2RE    LONDON  GREATER LONDON
1864140  260000000   W1D 6QF    LONDON  GREATER LONDON
764683   251000000  EC2M 4AA    LONDON  GREATER LONDON
236990   249500000  EC1V 4EX    LONDON  GREATER LONDON
2782021  217000000  WC1B 3NQ    LONDON  GREATER LONDON
1795744  207500000   HR2 7PP  HEREFORD   HEREFORDSHIRE
799549   201146664   CR0 2WF   CROYDON  GREATER LONDON

In [20]:
house_df.duplicated().sum()

np.int64(0)

In [7]:
crime_folder = Path(
    "/Users/bibhrajsaha/uk-housing-intelligence-platform/data/external/crime/2026-04"
)

crime_files = sorted(
    crime_folder.glob("*-street.csv")
)

len(crime_files)

41

In [8]:
crime_dfs = []

for file in crime_files:

    temp_df = pd.read_csv(file)

    crime_dfs.append(temp_df)

crime_df = pd.concat(
    crime_dfs,
    ignore_index=True
)

In [9]:
crime_df.shape

(478865, 12)

In [14]:
crime_df.isnull().sum()

Crime ID                  79799
Month                         0
Reported by                   0
Falls within                  0
Longitude                  6342
Latitude                   6342
Location                      0
LSOA code                 17733
LSOA name                 17733
Crime type                    0
Last outcome category     87385
Context                  478865
dtype: int64

In [15]:
(
    crime_df.isnull().sum()
    / len(crime_df)
    * 100
).round(2)

Crime ID                  16.66
Month                      0.00
Reported by                0.00
Falls within               0.00
Longitude                  1.32
Latitude                   1.32
Location                   0.00
LSOA code                  3.70
LSOA name                  3.70
Crime type                 0.00
Last outcome category     18.25
Context                  100.00
dtype: float64

In [16]:
crime_df.duplicated().sum()

np.int64(27103)

In [17]:
crime_df["Crime ID"].duplicated().sum()

np.int64(81505)

In [18]:
crime_df[
    crime_df["Longitude"].isnull()
].shape

(6342, 12)

In [19]:
crime_df[
    crime_df["Latitude"].isnull()
].shape

(6342, 12)